export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCES";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const UPDATE_PROFILE_PENDING = "REGISTER_PENDING";
export const UPDATE_PROFILE_SUCCESS = "REGISTER_SUCCESS";
export const UPDATE_PROFILE_FAIL = "REGISTER_FAIL";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_EXAMPLE_VENUE_BEGIN = "GET_EXAMPLE_VENUE_BEGIN";
export const GET_EXAMPLE_VENUE_SUCCESS = "GET_EXAMPLE_VENUE_SUCCESS";
export const GET_EXAMPLE_VENUE_FAIL = "GET_EXAMPLE_VENUE_FAIL";

export const GET_EXAMPLE_PACKAGES_BEGIN = "GET_EXAMPLE_PACKAGES_BEGIN";
export const GET_EXAMPLE_PACKAGES_SUCCESS = "GET_EXAMPLE_PACKAGES_SUCCESS";
export const GET_EXAMPLE_PACKAGES_FAIL = "GET_EXAMPLE_PACKAGES_FAIL";

export const GET_EXAMPLE_ORGANIZER_BEGIN = "GET_EXAMPLE_ORGANIZER_BEGIN";
export const GET_EXAMPLE_ORGANIZER_SUCCESS = "GET_EXAMPLE_ORGANIZER_SUCCESS";
export const GET_EXAMPLE_ORGANIZER_FAIL = "GET_EXAMPLE_ORGANIZER_FAIL";

export const GET_SEARCH_VENUE_BEGIN = "GET_SEARCH_VENUE_BEGIN";
export const GET_SEARCH_VENUE_SUCCESS = "GET_SEARCH_VENUE_SUCCESS";
export const GET_SEARCH_VENUE_FAIL = "GET_SEARCH_VENUE_FAIL";

export const GET_SEARCH_PACKAGES_BEGIN = "GET_SEARCH_PACKAGES_BEGIN";
export const GET_SEARCH_PACKAGES_SUCCESS = "GET_SEARCH_PACKAGES_SUCCESS";
export const GET_SEARCH_PACKAGES_FAIL = "GET_SEARCH_PACKAGES_FAIL";

export const GET_SEARCH_ORGANIZER_BEGIN = "GET_SEARCH_ORGANIZER_BEGIN";
export const GET_SEARCH_ORGANIZER_SUCCESS = "GET_SEARCH_ORGANIZER_SUCCESS";
export const GET_SEARCH_ORGANIZER_FAIL = "GET_SEARCH_ORGANIZER_FAIL";

export const GET_VENDOR_BEGIN = "GET_VENDOR_BEGIN";
export const GET_VENDOR_SUCCESS = "GET_VENDOR_SUCCESS";
export const GET_VENDOR_FAIL = "GET_VENDOR_FAIL";

export const GET_SEARCH_BEGIN = "GET_SEARCH_BEGIN";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAIL = "GET_SEARCH_FAIL";
export const GET_DETAIL_VENDOR_BEGIN = "GET_DETAIL_VENDOR_BEGIN";
export const GET_DETAIL_VENDOR_SUCCESS = "GET_DETAIL_VENDOR_SUCCESS";
export const GET_DETAIL_VENDOR_FAIL = "GET_DETAIL_VENDOR_FAIL";

export const GET_DETAIL_PACKAGE_BEGIN = "GET_DETAIL_PACKAGE_BEGIN";
export const GET_DETAIL_PACKAGE_SUCCESS = "GET_DETAIL_PACKAGE_SUCCESS";
export const GET_DETAIL_PACKAGE_FAIL = "GET_DETAIL_PACKAGE_FAIL";
