export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCES";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_USER = "GET_USER";
export const LOGOUT = "LOGOUT";

export const GET_EXAMPLE_VENUE_BEGIN = "GET_EXAMPLE_VENUE_BEGIN";
export const GET_EXAMPLE_VENUE_SUCCESS = "GET_EXAMPLE_VENUE_SUCCESS";
export const GET_EXAMPLE_VENUE_FAIL = "GET_EXAMPLE_VENUE_FAIL";

export const GET_EXAMPLE_PACKAGES_BEGIN = "GET_EXAMPLE_PACKAGES_BEGIN";
export const GET_EXAMPLE_PACKAGES_SUCCESS = "GET_EXAMPLE_PACKAGES_SUCCESS";
export const GET_EXAMPLE_PACKAGES_FAIL = "GET_EXAMPLE_PACKAGES_FAIL";

export const GET_EXAMPLE_ORGANIZER_BEGIN = "GET_EXAMPLE_ORGANIZER_BEGIN";
export const GET_EXAMPLE_ORGANIZER_SUCCESS = "GET_EXAMPLE_ORGANIZER_SUCCESS";
export const GET_EXAMPLE_ORGANIZER_FAIL = "GET_EXAMPLE_ORGANIZER_FAIL";
